# Generated by Django 5.0.1 on 2024-01-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='товар')),
                ('product_model', models.CharField(max_length=255, verbose_name='модель')),
                ('launch_date', models.DateField(verbose_name='дата выхода товара на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=255, verbose_name='страна')),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('number_home', models.IntegerField(verbose_name='номер дома')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='задолженность')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronic.product', verbose_name='товар')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electronic.seller', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'продавец',
                'verbose_name_plural': 'продавцы',
            },
        ),
    ]
