# Generated by Django 5.0.1 on 2024-01-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AddField(
            model_name='seller',
            name='level',
            field=models.CharField(choices=[('ZERO', '0'), ('FIRST', '1'), ('SECOND', '2')], default='DAILY', verbose_name='периодичность'),
        ),
    ]
