# Generated by Django 5.0.1 on 2024-01-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0002_alter_product_options_seller_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='level',
            field=models.CharField(choices=[('ZERO', '0'), ('FIRST', '1'), ('SECOND', '2')], verbose_name='уровень'),
        ),
    ]
