# Generated by Django 5.0.1 on 2024-01-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0003_alter_seller_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='level',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], verbose_name='уровень'),
        ),
        migrations.RemoveField(
            model_name='seller',
            name='product',
        ),
        migrations.AddField(
            model_name='seller',
            name='product',
            field=models.ManyToManyField(to='electronic.product', verbose_name='товар'),
        ),
    ]
